language: generic
sudo: required

services:
  - docker

branches:
  only:
    - develop
    - master
    - building

before_install:
  - docker pull francescoceruti/flatpack

before_script:
  - git clone -b gh-pages https://github.com/$TRAVIS_REPO_SLUG export/ &&
    cp -rf export/$TRAVIS_BRANCH/repo dist/Flatpak/
    || mkdir -p export/$TRAVIS_BRANCH

script:
  - cd dist/Flatpak
  # Patch the flatpak manifest to work with travis
  - python3 travis_flatpak.py
  # Run the build in a container, mounting the current directory
  # FIXME: if this fails at any stage the cache is not committed by travis
  - docker run --privileged -v ${PWD}:/src -i francescoceruti/flatpack src/build.sh $TRAVIS_BRANCH
  # Return into the build-dir
  - cd $TRAVIS_BUILD_DIR

cache:
  directories:
    # Flatpak build cache, avoid rebuilding unchanged modules
    - $TRAVIS_BUILD_DIR/dist/Flatpak/.flatpak-builder

before_deploy:
  - rm -rf export && mkdir -p export/$TRAVIS_BRANCH
  - cp -rf dist/Flatpak/repo/ export/$TRAVIS_BRANCH
  - cp -rf dist/Flatpak/linux-show-player.flatpakref export/$TRAVIS_BRANCH
  - sed -i -- 's/master/'$TRAVIS_BRANCH'/g' export/$TRAVIS_BRANCH/linux-show-player.flatpakref

deploy:
  edge:
    branch: v1.8.47
  provider: pages
  local_dir: export
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    all_branches: true
