language: generic
sudo: required

services:
  - docker

branches:
  only:
    - develop
    - master
    - building

before_install:
  - docker pull francescoceruti/flatpack

before_script:
  # Clone the flatpak repository locally
  - git clone -b gh-pages https://github.com/$TRAVIS_REPO_SLUG export/
  # Copy the repository into the "building" directory
  - cp -rf export/repo dist/Flatpak/ || true

script:
  # Enter the flatpak buid directory
  - cd dist/Flatpak
  # Patch the flatpak manifest to work with travis
  - python3 travis_flatpak.py
  # Run the build in a container, mounting the current directory
  # FIXME: if this fails at any stage the cache is not committed by travis
  - docker run --privileged -v ${PWD}:/src -i francescoceruti/flatpack src/build.sh $TRAVIS_BRANCH
  # Return into the build-dir
  - cd $TRAVIS_BUILD_DIR

cache:
  directories:
    # Flatpak build cache, avoid rebuilding unchanged modules
    - $TRAVIS_BUILD_DIR/dist/Flatpak/.flatpak-builder

before_deploy:
  # Clean the export directory
  - rm -rf export/ && mkdir -p export/
  # Copy the updated repository into the export directory
  - cp -rf dist/Flatpak/repo/ export/
  # Copy the flatpakrepo file
  - cp -rf dist/Flatpak/linux-show-player.flatpakrepo export/linux-show-player.flatpakrepo

deploy:
  edge:
    branch: v1.8.47
  provider: pages
  local_dir: export
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    all_branches: true
